name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@67545f50bc9e557eaf43a74395cc1461416d0035
    permissions:
      contents: write
    with:
      modules: >-
        ["SmokeAPI"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll

      config: Debug
